### ISSUE TITLE
Rozbité přihlášení k odběru newsletteru

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#300]
Aktuálně nám neběží funkce [/api/newsletter](https://cesko.digital/api/newsletter) (HTTP 500), kvůli tomuhle:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/zoul/Sites/cesko.digital/api/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /Users/zoul/Sites/cesko.digital/api/node_modules/node-fetch/src/index.js from /Users/zoul/Sites/cesko.digital/api/newsletter.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/zoul/Sites/cesko.digital/api/node_modules/node-fetch/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1126:13)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/vercel/node_modules/ts-node/src/index.ts:832:44)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/zoul/Sites/cesko.digital/api/newsletter.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Module.m._compile (/usr/local/lib/node_modules/vercel/node_modules/ts-node/src/index.ts:839:23) {
  code: 'ERR_REQUIRE_ESM'
```

Moc tomu nerozumím, tipuju, že jde o nějaký souběh s Vercelem à la https://github.com/vercel/next.js/issues/25454. A tipuju, že je to regrese zanesená v 3ffc4f6, takže pokud rychle nenajdeme řešení, můžeme to dočasně revertnout a vrátit, až najdeme řešení tohoto problému.

**Comment by zoul** [comment]
Zkusil jsem technickou podporu Vercelu, case `#00047262`.

**Comment by zoul** [comment]
Ještě to s Vercelem ladíme, mám menší ukázkové repo: https://github.com/zoul/vercel-test.
