### ISSUE TITLE
Přidat jednoduché E2E testy

### ISSUE THREAD

**Issue by zoul** [cesko-digital/web#414]
Ideálně asi přes Playwright, [viz dokumentaci](https://nextjs.org/docs/testing). @karmi byl pro E2E testy, měl bys tip, co by bylo rozumné testovat?

**Comment by tomburger** [comment]
Ahoj, jestli hledáte nějakého dobrovolníka, co se naučí Playwright a jak ho použít na E2E testy,  tak já se hlásím :-)
Mám to už nějakou dobu na check-listu...

**Comment by zoul** [comment]
Super! Navrhuju ale nejdřív odbavit #418, protože bez toho bychom museli řešit, jak se v rámci těch E2E testů dostat do Airtable. Domluvím se ještě s @karmi a ozveme se. Díky!

**Comment by zoul** [comment]
Tohle je hotovo, díky moc, Tome!

**Comment by zoul** [comment]
Tome, ještě se nám to docela často [samo rozbíjí](https://github.com/cesko-digital/web/runs/5091218741?check_suite_focus=true), tohle je určitě false negative. Můžeš mrknout, čím by to mohlo být?

**Comment by zoul** [comment]
Karel posílal ve Slacku tohle:

![image](https://user-images.githubusercontent.com/95329/152937151-6637723e-034b-4c61-be87-55f578ed78d1.png)

Nepodaří se ti to nějak reprodukovat lokálně? Akorát koukám, že v GitHub Actions nám to padá na něčem jiném:

```
2) e2e/homepage.spec.ts:10:1 › link from home page to join site ==================================
[26](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:26)

[27](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:27)
    Error: expect(received).toContainText(expected)
[28](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:28)

[29](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:29)
    Expected string: "Skrz jedničky a nuly"
[30](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:30)
    Received string: "Server Error"
[31](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:31)
    Call log:
[32](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:32)
      - expect.toContainText with timeout 5000ms
[33](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:33)
      - waiting for selector "h1"
[34](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:34)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[35](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:35)
      -   unexpected value "Server Error"
[36](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:36)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[37](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:37)
      -   unexpected value "Server Error"
[38](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:38)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[39](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:39)
      -   unexpected value "Server Error"
[40](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:40)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[41](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:41)
      -   unexpected value "Server Error"
[42](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:42)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[43](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:43)
      -   unexpected value "Server Error"
[44](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:44)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[45](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:45)
      -   unexpected value "Server Error"
[46](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:46)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[47](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:47)
      -   unexpected value "Server Error"
[48](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:48)
      -   selector resolved to <h1 id="nextjs__container_errors_label">Server Error</h1>
[49](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:49)
      -   unexpected value "Server Error"
[50](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:50)

[51](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:51)

[52](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:52)
      10 | test("link from home page to join site", async ({ page }) => {
[53](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:53)
      11 |   await page.goto("/");
[54](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:54)
    > 12 |   await expect(page.locator("h1")).toContainText("Skrz jedničky a nuly");
[55](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:55)
         |                                    ^
[56](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:56)
      13 |   await page.click("text=Chci se zapojit");
[57](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:57)
      14 |   await expect(page).toHaveURL("https://join.cesko.digital/");
[58](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:58)
      15 | });
[59](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:59)

[60](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:60)
        at /home/runner/work/web/web/tests/e2e/homepage.spec.ts:12:36
[61](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:61)
        at /home/runner/work/web/web/node_modules/@playwright/test/lib/workerRunner.js:529:7
[62](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:62)
        at WorkerRunner._runFn (/home/runner/work/web/web/node_modules/@playwright/test/lib/workerRunner.js:575:7)
[63](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:63)
        at WorkerRunner._runTestWithBeforeHooks (/home/runner/work/web/web/node_modules/@playwright/test/lib/workerRunner.js:523:20)
[64](https://github.com/cesko-digital/web/runs/5093823645?check_suite_focus=true#step:6:64)
```

**Comment by zoul** [comment]
Přidal jsem v dcb45b651a1b55a03a58b77e5de1f051a03ec8e9.
